### ISSUE TITLE
ModPorter::InvalidSignature in ScreensController#create != 8rFPaOuZX6yzocNSh7d41b14VRE

### ISSUE THREAD

**Issue by diptisampath** [actionrails/modporter#14]
We use Rails version - 2.1.1 and Passenger version - 2.2.4.
We had followed all the steps given in github to install modporter and make changes in the conf file.

However we got the following error.

ModPorter::InvalidSignature in ScreensController#create != 8rFPaOuZX6yzocNSh7d41b14VRE

vendor/plugins/actionrails-modporter-plugin-361dda5/lib/mod_porter.rb:95:in `check_signature!' vendor/plugins/actionrails-modporter-plugin-361dda5/lib/mod_porter.rb:84:in`normalize_mod_porters' 
vendor/plugins/actionrails-modporter-plugin-361dda5/lib/mod_porter.rb:48:in `each'
vendor/plugins/actionrails-modporter-plugin-361dda5/lib/mod_porter.rb:48:in`normalize_mod_porters' 
vendor/rails/activesupport/lib/active_support/callbacks.rb:173:in `send'

 Request Parameters: {"screens"=>[{"uploaded_data"=>{"filename"=>"Screenshot.png"}}, {"uploaded_data"=>{"content_type"=>"image/png"}}, {"uploaded_data"=>{"path"=>"/tmp/porter/apreqCDWWld"}}, {"uploaded_data"=>{"signature"=>"oQTODf21ZQoVZXXwViq0geUGvPI="}}], "submit"=>"Upload All", "authenticity_token"=>"e7b36297f76be74ab4c88d3ce19248066447b05e", "vuln_id"=>"70", "audit_id"=>"19"} 

The request parameter when we do not use Modporter is as follows.

Processing ScreensController#create (for 127.0.0.1 at 2010-02-25 10:54:28) [POST]
  Session ID: eca4d8990a8bae473b1d6ad262952a08
  Parameters: {"audit_id"=>"5", "submit"=>"Upload All", "action"=>"create", "authenticity_token"=>"cd16fc2480319c412c8b2846a79ca240dafac521", "vuln_id"=>"8", "controller"=>"screens", "screens"=>[{"uploaded_data"=>#ActionController::UploadedStringIO:0xb4647e04}]}

Kindly fix the issue at the earliest.
Thanks!

**Comment by johncos** [comment]
Configure the plugin by providing the shared secret in application.rb :

  class ApplicationController < ActionController::Base
    self.mod_porter_secret = "secret"
  end
